// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSidd1oIzWbhOZ2lQKpSytUsiMu9qQTWI',
    appId: '1:992363592270:web:9b0368f6bf1b30ea25e11f',
    messagingSenderId: '992363592270',
    projectId: 'expence-tracker-app-4507b',
    authDomain: 'expence-tracker-app-4507b.firebaseapp.com',
    storageBucket: 'expence-tracker-app-4507b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrch4qtiObd2W9NHX0QyXhTY0SAFYmEI',
    appId: '1:992363592270:android:39282dc5a206f95b25e11f',
    messagingSenderId: '992363592270',
    projectId: 'expence-tracker-app-4507b',
    storageBucket: 'expence-tracker-app-4507b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA21iRqMKLN1A09YxLgUVoxhlvNDyqZLcA',
    appId: '1:992363592270:ios:5f5b64a588112a2725e11f',
    messagingSenderId: '992363592270',
    projectId: 'expence-tracker-app-4507b',
    storageBucket: 'expence-tracker-app-4507b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA21iRqMKLN1A09YxLgUVoxhlvNDyqZLcA',
    appId: '1:992363592270:ios:5fbf18692b1951d025e11f',
    messagingSenderId: '992363592270',
    projectId: 'expence-tracker-app-4507b',
    storageBucket: 'expence-tracker-app-4507b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
